apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-2
  labels:
    app: capstone-2
  namespace: default
spec:
  replicas: 2
  progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: capstone-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone-2
    spec:
      containers:
        - image: ekram321/capstone-2
          imagePullPolicy: Always
          name: capstone-2
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone-2
  labels:
    app: capstone-2
spec:
  type: LoadBalancer
  selector:
    app: capstone-2
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP