version: 2.1


jobs:
  lint:
    docker: 
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv capstone
            . capstone/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . capstone/bin/activate
            make lint  
  
   build-push-docker-image:
    machine: true
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: build and push docker image
          command: |
            #Login to docker hub
            docker login --username $DOCKERHUB_USER --password $DOCKERHUB_PWD
            # Build image and add a descriptive tag
            docker build --tag=capstone-2 .
            # List docker images
            docker image ls
            # Push image to a docker repository
            docker tag capstone-2 ekram321/capstone-2
            docker push ekram321/capstone-2

workflows:
  deployment:
    jobs:
      - lint
      - build-push-docker-image:
          requires:
            - lint
